version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=vehicles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=vehicles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
